version: '2'

services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    container_name: zk_node01
    ports:
      - 12181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - zk_node01_data:/data
      - zk_node01_log:/datalog
    networks:
      - zk_kafka

  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    container_name: zk_node02
    ports:
      - 22181:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - zk_node02_data:/data
      - zk_node02_log:/datalog
    networks:
      - zk_kafka

  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    container_name: zk_node03
    ports:
      - 32181:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - zk_node03_data:/data
      - zk_node03_log:/datalog
    networks:
      - zk_kafka
 
  kafka:
    image: wurstmeister/kafka
    restart: always
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.16.8.54
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181/kafka1,zoo2:2181/kafka1,zoo3:2181/kafka1 
 
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - zk_kafka

  kafka_manager:
    image: pllsxyc/kafka-manager
    restart: always
    hostname: kafka_manager
    container_name: kafka_manager
    ports:
      - 8989:8080
    environment:
      ZK_HOSTS: zoo1:2181/kafka1,zoo2:2181/kafka1,zoo3:2181/kafka1
    networks:
      - zk_kafka
    depends_on:
      - zoo1
      - zoo2
      - zoo3
      - kafka

  kafkaoffsetmonitor:
    image: pllsxyc/kafkaoffsetmonitor
    restart: always
    hostname: kafkaoffsetmonitor
    container_name: kafkaoffsetmonitor
    ports:
      - 9999:9999
    networks:
      - zk_kafka
    depends_on:
      - zoo1
      - zoo2
      - zoo3
      - kafka   

networks:
  zk_kafka:
    driver: bridge

volumes:
  zk_node01_data:
    driver: local
  zk_node01_log:
    driver: local
  zk_node02_data:
    driver: local
  zk_node02_log:
    driver: local
  zk_node03_data:
    driver: local
  zk_node03_log:
    driver: local